services:
  postgres:
    image: postgres:16
    container_name: conmed-db
    command: -c listen_addresses='*'
    environment:
      POSTGRES_USER: conmed
      POSTGRES_PASSWORD: conmed
      POSTGRES_DB: conmed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conmed
    restart: unless-stopped

  pgadmin:
    container_name: conmed-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - conmed
    restart: unless-stopped

networks:
  conmed:
    driver: bridge

volumes:
  postgres_data:
  pgadmin: